doc-warnings: no
test-warnings: no
strictness: medium
autodetect: yes
pylint:
    disable:
        - logging-too-many-args
        - too-many-function-args
        - too-many-arguments
        - pointless-string-statement
# requirements:
#     - deps/core.txt
#     - deps/test.txt
ignore-paths:
    - docs
    - pics
    - sim
    - sounds
    - tmp
    - otherLibs
    - lib_old
# ignore-patterns:
#     - ^soccer/Adafruit_.*\.py$
python-targets:
    - 2
