doc-warnings: no
test-warnings: no
strictness: medium
autodetect: yes
# requirements:
#     - deps/core.txt
#     - deps/test.txt
ignore-paths:
    - docs
    - pics
    - sim
    - sounds
    - tmp
    - IMU
ignore-patterns:
    - ^soccer/Adafruit_.*\.py$
python-targets:
    - 2
